### ISSUE TITLE
Failure to reupload to Pursuit

### ISSUE THREAD

**Issue by hdgarrood** [cdepillabout/purescript-email-validate#1]
Hey,

A couple of the versions that were previously on Pursuit are no longer there, because I failed to migrate them to 0.8. Sorry.

It was because of the `import Prelude (..)` syntax, which was removed between 0.8.0-RC1 and 0.8.0 proper. Probably the best fix (if you want to) is just to change it back to `import Prelude`, tag a patch version, and publish.

**Comment by cdepillabout** [comment]
Thanks for the heads up!  I updated and uploaded to Pursuit:

https://pursuit.purescript.org/packages/purescript-email-validate/1.0.6
