### ISSUE TITLE
Needs license

### ISSUE THREAD

**Issue by justinwoo** [cdepillabout/purescript-email-validate#3]
We do need a license and some other stuff added for Pulp to let us publish this though. @cdepillabout, could you add a license file and update the fields in bower.json/package.json?

**Comment by cdepillabout** [comment]
Thanks for letting me know about this.  I've added a LICENSE file, updated the bower.json file, and released as version 1.0.7:

https://pursuit.purescript.org/packages/purescript-email-validate/1.0.7
